### ISSUE TITLE
Should show error message in older PHP.

### ISSUE THREAD

**Issue by torounit** [megumiteam/cf7-mautic#10]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? |
| Feature request? | 
| Enhancement? | x

## Description:

Can't activate plugin in PHP 5.5. 
But can update the plugin while it is activated.

Should display a notice for user.

| Q   | A
| --- | ---
| WordPress  version | 4.7.3
| PHP version |  5.5.38

**Comment by hideokamoto** [comment]
👍
