### ISSUE TITLE
Not compatible with WP 4.6

### ISSUE THREAD

**Issue by eth4ever** [megumiteam/cf7-mautic#9]
The plugin is not compatible with WP 4.6. Is it possible to upgrade to the most recent version of WP?

## Description:
After installing and activating the plugin this error appears:

> Parse error: syntax error, unexpected '[' in /home/sites/site46280/web/wp-content/plugins/cf7-mautic-extention/inc/class.submit.php on line 156

**Comment by hideokamoto** [comment]
Your PHP version is old.
Please upgrade PHP versions.

> To run WordPress we recommend your host supports:
> PHP version 5.6 or greater
> MySQL version 5.6 or greater OR MariaDB version 10.0 or greater
> https://wordpress.org/about/requirements/

**Comment by eth4ever** [comment]
Thanks. That was the problem.
